[visualization]
name = PR-SoCal
tile_corrections = tile_corrections.csv
region_dir = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\Regions\SouthernCA
areas_file = areas_socal-pr.ini

[region.arvin]
display_name = Arvin/OakCreek
route_prefix = 310
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\ArvinOakCreekBranches
enabled_by_default = false

[region.bakersfield]
display_name = Bakersfield
route_prefix = 250
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\BNSF_BakersfieldSub
enabled_by_default = false

[region.barstow]
display_name = Barstow/Yermo
route_prefix = 150
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\BarstowYermo
enabled_by_default = false

[region.cajon]
display_name = Cajon
route_prefix = 120
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\BNSF_CajonSub
enabled_by_default = false

[region.modesto]
display_name = Fresno/Modesto
route_prefix = 340
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\BNSF_UP_FresnoModesto
enabled_by_default = false

[region.mojave]
display_name = Mojave
route_prefix = 100
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\BNSF_MojaveSub
enabled_by_default = false

[region.needles]
display_name = Needles
route_prefix = 110
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\BNSF_NeedlesSub
enabled_by_default = false

[region.sanbernardino]
display_name = SanBernardino
route_prefix = 200
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\BNSF_SanBernardinoSub
enabled_by_default = true

[region.seligman]
display_name = Seligman
route_prefix = 130
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\BNSF_SeligmanSub
enabled_by_default = false

[region.trona]
display_name = Trona
route_prefix = 320
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\TronaRailway
enabled_by_default = false

[region.upfresno]
display_name = UP_Fresno
route_prefix = 101
directory = C:\Run8Studios - PR\Run8 Train Simulator V3\Content\V3Routes\UP_FresnoSub_South
enabled_by_default = false

[tile_based_plot]
home_tile = 92,9
tile_width = 842.3
tile_height = 1023.2

[colors]
# Track colors
track = #0066cc
track_selected = #ff0000
track_hover = #90D5FF
switch = #800080
industry_track = #00aa00
# Background color (for tile mode)
background = #e4eaed

# Signal colors
signal_absolute = #FF6B35
signal_intermediate = #FFD700
signal_border_single = #000000
signal_border_stacked = #87CEEB

[output]
output_dir = ./output/socal-pr/

# route info
;BNSF_MojaveSub	100	SouthernCA
;UP_FresnoSub_South 101 SouthernCA
;BNSF_NeedlesSub	110	SouthernCA
;BNSF_CajonSub	120	SouthernCA
;BNSF_SeligmanSub	130	SouthernCA
;CSX_ALine	140	HRS_Southeast
;BarstowYermo	150	SouthernCA
;CSX_SelkirkTerminal	170	SelkirkRegion
;BNSF_SanBernardinoSub	200	SouthernCA
;CSX_Waycross	210	HRS_Southeast
;CSX_Fitzgerald	230	HRS_Southeast
;CSX_MohawkSub	240	SelkirkRegion
;BNSF_BakersfieldSub	250	SouthernCA
;SP-UP_RosevilleSub	260	NorthernCA
;SP-NS_AGS_Phase01	280	GulfCoast
;NS_PittsburghLine_East	290	Pennsylvania
;NS_South_Fork_Secondary	291	Pennsylvania
;ArvinOakCreekBranches	310	SouthernCA
;TronaRailway	320	SouthernCA
;BNSF_UP_FresnoModesto	340	SouthernCA
;CSX_Savannah	380	HRS_Southeast
;CSX_PortOfSavannah	381	HRS_Southeast
;CSX_Baldwin	390	HRS_Southeast
